title: "Everberry Events"
description: "Everberry Events - Cultivating Connections"
url: "https://www.everberryevents.com"
baseurl: ""

logo:
  desktop: "images/everberryevents/logo/Original_on_transparent.png"
  desktop_height: "32px"
  desktop_width: "120px"

sass:
  style: compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - LICENSE
  - README.md
