title: "Everberry Events"
description: "Everberry Events - Cultivating Connections"
url: ""
baseurl: ""

logo:
  desktop: "images/everberryevents/logo/Original_on_transparent.png"
  desktop_height: "32px"
  desktop_width: "120px"

sass:
  style: compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - about.md
  - services.md
  - team.md
  - contact.md
  - build_error.log
  - debug.log
  - gem_env.log
  - gem_list.log
  - builtatlightspeed.json
  - _services
  - _team
